name: deploy on push production branch
on:
  push:
    branches:
      - prod # 确保只在 prod 分支触发

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v3

      # --- 新增：网络连通性测试 ---
      - name: Test network connectivity
        run: |
          echo "Testing connectivity to ${{ secrets.HOST }}:${{ secrets.SSH_PORT }}"
          timeout 30 bash -c 'while ! echo > /dev/tcp/${{ secrets.HOST }}/${{ secrets.SSH_PORT }} 2>/dev/null; do sleep 1; done' || false
          echo "Connection to ${{ secrets.HOST }}:${{ secrets.SSH_PORT }} established"

      # --- 关键步骤：设置目标目录权限 ---
      - name: Prepare directory permissions
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 300s  # 延长超时时间
          args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -o ConnectTimeout=60
            -o ConnectionAttempts=3
          script: |
            echo "Starting to prepare directory permissions..."
            sudo mkdir -p /var/www/html
            echo "Directory created or already exists."
            sudo chown -R ubuntu:ubuntu /var/www/html
            echo "Directory ownership set to ubuntu:ubuntu."
            sudo chmod -R 755 /var/www/html
            echo "Directory permissions set to 755."

      # --- 关键步骤：复制文件 ---
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1
          timeout: 300s  # 延长超时时间
          # 可选：添加 force: true 如果希望覆盖目标文件

      # --- 关键步骤：恢复目录权限（如果需要） ---
      - name: Restore directory permissions if needed
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 300s  # 延长超时时间
          args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -o ConnectTimeout=60
            -o ConnectionAttempts=3
          script: |
            echo "Starting to restore directory permissions..."
            # 恢复所有者为 root (如果需要)
            sudo chown -R root:root /var/www/html
            echo "Directory ownership set to root:root."
            # 确保 root 也能读取和执行
            sudo chmod -R 755 /var/www/html
            echo "Directory permissions set back to 755 for root."