name: deploy on push production branch
on:
  push:
    branches:
      - prod
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v3
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.SSH_USER_NAME}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1
                              - name: set the ubuntu user as the owner of the /var/www/html directory for unbuntu 24+
                              uses: appleboy/ssh-action@v1.2.0
                              with:
                                host: ${{ secrets.HOST }}
                                username: ${{ secrets.SSH_USER_NAME }}
                                key: ${{ secrets.SSH_KEY }}
                                script: |
                                  sudo chown -R ubuntu /var/www/html
                                  - name: set the root user back as the owner of the /var/www/html directory for unbuntu 24+
                                        uses: appleboy/ssh-action@v1.2.0
                                        with:
                                          host: ${{ secrets.HOST }}
                                          username: ${{ secrets.SSH_USER_NAME }}
                                          key: ${{ secrets.SSH_KEY }}
                                          script: |
                                           sudo chown -R root /var/www/html